# Generated by Django 5.1 on 2026-05-20 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="email",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="participant",
            name="phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
