# Generated by Django 5.1 on 2026-05-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmessage",
            options={"ordering": ["created_at"]},
        ),
        migrations.AddField(
            model_name="chatroom",
            name="last_activity_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="unread_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customerkey",
            name="allow_anonymous",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customerkey",
            name="history_limit",
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name="customerkey",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customerkey",
            name="plan",
            field=models.CharField(default="FREE", max_length=20),
        ),
        migrations.AddField(
            model_name="customerkey",
            name="show_social_links",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customerkey",
            name="social_facebook",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customerkey",
            name="social_phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="customerkey",
            name="social_zalo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customerkey",
            name="widget_position",
            field=models.CharField(default="bottom-right", max_length=20),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["chat_room", "created_at"],
                name="chat_chatme_chat_ro_81da8a_idx",
            ),
        ),
    ]
