# Generated by Django 5.1 on 2026-05-20 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerkey",
            name="allow_anonymous",
            field=models.BooleanField(default=True),
        ),
    ]
