# Generated by Django 5.1 on 2026-05-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_customerkey_allow_anonymous"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerkey",
            name="history_limit",
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name="customerkey",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customerkey",
            name="plan",
            field=models.CharField(default="FREE", max_length=20),
        ),
    ]
